### ISSUE TITLE
Home tab

### ISSUE THREAD

**Issue by rdezic276** [rdezic276/SwensonBBQ#1]
all tabs stay except for the home tab we need to fix the code to make sure when you have the home tab selected it stays. move tabs around and center the tabs. Add a button for smaller screens.

**Comment by Wicksey1818** [comment]
Fixed up the "Home" portion of the menu and moved around the "Information" link as well.

**Comment by Wicksey1818** [comment]
Tried to get the "hamburger" icon to work. Got it to pop up when the page was made smaller, but it also messed up the color of the background to look very static. So instead I made it so that the nav-bar is only as long as the amount of the links in the bar, but it doesn't collapse with the page. Also added individual dividing lines to the nav-bar to make it look prettier :D
